name: Demo-2
on: 
    workflow_dispatch:
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Create a text file
          run: echo "hello, world" > hello.txt
    
    test: 
        runs-on: ubuntu-latest
        steps:
        - name: list file
          run: ls -l
        - name: test file
          run: cat hello.txt |grep -i "hello"