name: Demo-2
on: 
    workflow_dispatch:
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Create a text file
          run: echo "hello, world" > hello.txt
        - uses: actions/upload-artifact@v4
          with:
            name: hello-file
            path: hello.txt
    
    test: 
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/download-artifact@v8
          with:
            name: hello-file
        - name: list file
          run: ls -l
        - name: test file
          run: cat hello.txt |grep -i "hello"