name: My first workflow
on:
  push:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Welcome message
          run: echo "Welcome to GitHub Actions"
        - name: list files
          run: ls -l
        - name: readme file
          run: cat README.md
        
