name: My first workflow
on:
  push:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: install cowsay
          run: sudo apt-get install cowsay -y
        - name: execute cowsay
          run: cowsay -f dragon "Hello, World!" >> dragon.txt
        - name: Sleep for 30 seconds
          run: seleep 30
    
    test_jobs_2: 
        runs-on: ubuntu-latest
        steps:
        - name: sleeep 10 seconds
          run: sleep 10
        - name: Test file Exists
          run: grep -i "dragon" dragon.txt


    deploy_job_3:
        runs-on: ubuntu-latest
        steps: 
        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: Echo Deploying ---------
        
        


  

    