name: My first workflow
on:
  workflow_dispatch:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: install cowsay
          run: sudo apt-get install cowsay -y
        - name: execute cowsay
          run: cowsay -f dragon "Hello, World!" >> dragon.txt
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    test_jobs_2: 
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v8
          with:
            name: dragon-text-file


        - name: Test file Exists
          run: grep -i "dragon" dragon.txt


    deploy_job_3:
        needs: test_jobs_2
        runs-on: ubuntu-latest
        steps: 
        - name: Download artifact
          uses: actions/download-artifact@v8
          with:
            name: dragon-text-file
        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: Echo Deploying ---------
        
        


  

    