name: Variable and Secrets Example
on: 
  workflow_dispatch: # Runs manually
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
    
jobs:

  ################## Environment Variables at JOB Level ##################
    # docker:
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Docker build
    #     env:
    #       CONTAINER_REGISTRY: docker.io
    #       DOCKER_USERNAME: webdevloper
    #       IMAGE_NAME: github-actions-nginx
    #     run: echo dockr build -t {{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest   

    #   - name: Docker login
    #     env:
    #       CONTAINER_REGISTRY: docker.io
    #       DOCKER_USERNAME: webdevloper
    #       DOCKER_PASSWORD: 312514@Sc
    #     run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $CONTAINER_REGISTRY

    #   - name: Docker publish
    #     env:
    #       CONTAINER_REGISTRY: docker.io
    #       DOCKER_USERNAME: webdevloper
    #       IMAGE_NAME: github-actions-nginx
    #     run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    # deploy:
    #   needs: docker
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Deploy to server
    #     env: 
    #       CONTAINER_REGISTRY: docker.io
    #       DOCKER_USERNAME: webdevloper
    #       IMAGE_NAME: github-actions-nginx
    #     run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest



    docker:
      runs-on: ubuntu-latest
      steps:
      - name: Docker build
        run: echo dockr build -t {{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest   

      - name: Docker login
        env:
          DOCKER_PASSWORD: 312514@Sc
        run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{ secrets.DOCKER_PASSWORD }} $CONTAINER_REGISTRY

      - name: Docker publish
        run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

    deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Deploy to server
        run: | 
          echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
          sleep 600s
        